# docker-compose.yml
version: '3'
services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/certs:/etc/nginx/certs
      - ../../public:/usr/share/nginx/html
    extra_hosts:
      - "host.docker.internal:host-gateway"