# docker-compose.yml
version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./localhost.crt:/etc/nginx/certs/localhost.crt
      - ./localhost.key:/etc/nginx/certs/localhost.key
    extra_hosts:
      - "host.docker.internal:host-gateway"